server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  kafka: 
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all # Luu tat ca cac message vao disk
      # retries: 3  # Số lần retry khi gửi thất bại, comment vi khi
      # bat enable.idempotence thi retries = Integer.MAX_VALUE
      properties:
        # Đảm bảo không gửi duplicate message
        enable.idempotence: true
        # So request gui song song, nhung kafka tu set = 5 khi co enable.idempotence
        # max.in.flight.requests.per.connection: 5
jwt:
  secret: ${JWT_SECRET}
  expiration_access: 3000000000 # milliseconds, tinh ra la = 3000s, dung de test login
  expiration_refresh: 604800000 # milliseconds, tinh ra la = 7 * 24 * 60 * 1000

recaptcha:
  secret: ${RECAPTCHA_SECRET}
  verify-url: https://www.google.com/recaptcha/api/siteverify

otp:
  expiry-minutes: 600

springdoc:
  # Thay doi duong dan vao giao dine Swagger UI
  # Mac dinh la /swagger-ui.html
  swagger-ui:
    path: /user/api-docs/swagger-ui.html

  # Thay doi duong dan file du lieu (apo-docs)
  # Mac dinh la /v3/api-docs
  api-docs:
    path: /user/api-docs/v3/api-docs

