services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # Specifies whether Elasticsearch should form a multiple-node cluster.
        ## Defaults to multi-node, which means that Elasticsearch discovers other nodes when forming a cluster
        ## and allows other nodes to join the cluster later.
        ## If set to single-node, Elasticsearch forms a single-node cluster and suppresses the timeout
        ## set by cluster.publish.timeout
      - xpack.security.enabled=false # Defaults to true,
        # which enables Elasticsearch security features on the node.
        # This setting must be enabled to use Elasticsearch’s authentication, authorization and audit features.
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Set heap size cho JVM cua elastic search
      # -Xms512m - heap ban dau
      # -Xmx512m - heap toi da
      # ca hai bang nhau => heap khong thay doi trong luc chay
      # - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    mem_limit: 2g
    networks:
      - backend
  #    ulimits:
  #      memlock: # khoa ram, ko cho swap data ra disk khi ram bi day bo nho, phai ket hop voi
  #               # environment: bootstrap.memory_lock=true
  #        soft: -1 # gioi han duoi, -1 nghia la unlimited
  #        hard: -1 # gioi han tren, -1 nghia la unlimited
  #    healthcheck:
  #      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch
        # condition: service_healthy
        # se khong duoc kich hoat vi da disable healthcheck o elastic search
  #    healthcheck:
  #      test:
  #        [
  #          "CMD-SHELL",
  #          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
  #        ]
  #      interval: 10s
  #      timeout: 10s
  #      retries: 120

  db1:
    image: postgres:15-alpine
    container_name: db1
    restart: unless-stopped
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./db1_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  db2:
    image: postgres:15-alpine
    container_name: db2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./db2_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  broker:
    image: apache/kafka:3.9.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - backend

  # gateway:
  #   build: ./gateway
  #   container_name: gateway
  #   env_file:
  #     - ./gateway/.env.docker
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - user
  #     - main
  #   networks:
  #     - backend

  # main:
  #   build: ./main
  #   container_name: main
  #   env_file:
  #     - ./main/.env.docker
  #   ports:
  #     - "8082:8082"
  #   volumes:
  #     - ./logs_from_docker/main:/logs
  #   depends_on:
  #     - db2
  #     - elasticsearch
  #     - broker
  #   networks:
  #     - backend

  # user:
  #   build: ./user
  #   container_name: user
  #   env_file:
  #     - ./user/.env.docker
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./logs_from_docker/user:/logs
  #   depends_on:
  #     - db1
  #     - broker
  #   networks:
  #     - backend

  # worker:
  #   build: ./worker
  #   container_name: worker
  #   env_file:
  #     - ./worker/.env.docker
  #   ports:
  #     - "8083:8083"
  #   volumes:
  #     - ./logs_from_docker/worker:/logs
  #   depends_on:
  #     - main
  #     - db2
  #     - elasticsearch
  #     - broker
  #   networks:
  #     - backend

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./logs_from_docker/user:/var/log/app/user:ro
      - ./logs_from_docker/main:/var/log/app/main:ro
      - ./logs_from_docker/worker:/var/log/app/worker:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat_data:/usr/share/filebeat/data
    networks:
      - backend
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy
    command: filebeat -e -strict.perms=false

networks:
  backend:
    driver: bridge

volumes:
  elasticsearch_data:
  db1_data:
  db2_data:
  kafka_data:
  filebeat_data:
