services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # Specifies whether Elasticsearch should form a multiple-node cluster.
      ## Defaults to multi-node, which means that Elasticsearch discovers other nodes when forming a cluster and allows other nodes to join the cluster later. If set to single-node, Elasticsearch forms a single-node cluster and suppresses the timeout set by cluster.publish.timeout
      - xpack.security.enabled=false # Defaults to true,
        # which enables Elasticsearch security features on the node.
        # This setting must be enabled to use Elasticsearch’s authentication, authorization and audit features.
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Set heap size cho JVM cua elastic search
      # -Xms512m - heap ban dau -Xms512m heap toi da, ca hai bang nhau => heap khong thay doi trong luc chay
      # - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    mem_limit: 2g
    networks:
      - elk-network
#    ulimits:
#      memlock: # khoa ram, ko cho swap data ra disk khi ram bi day bo nho, phai ket
                ## hop voi environment: bootstrap.memory_lock=true
#        soft: -1 # gioi han duoi, -1 nghia la unlimited
#        hard: -1 # gioi han tren, -1 nghia la unlimited
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - elasticsearch
        # condition: service_healthy
        # se khong duoc kich hoat vi da disable healthcheck o elastic search
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120
networks:
  elk-network:
    driver: bridge

volumes:
  elasticsearch_data:
