spring:
  mvc: # de cho endpoint nao ko co define thi tra ve message trong GlobalExceptionHandler
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false # de cho endpoint nao ko co define thi tra ve message trong GlobalExceptionHandler
      
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

  application:
    name: main

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none  # ko tu dong sync entity voi database (nguy hiem)

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all # Luu tat ca cac message vao disk
      # retries: 3  # Số lần retry khi gửi thất bại, comment vi khi
      # bat enable.idempotence thi retries = Integer.MAX_VALUE
      properties:
        # Đảm bảo không gửi duplicate message
        enable.idempotence: true
        # So request gui song song, nhung kafka tu set = 5 khi co enable.idempotence
        # max.in.flight.requests.per.connection: 5

server:
  port: ${SERVER_PORT:8082}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}

assessment:
  minimum: 8.0

springdoc:
  # Thay doi duong dan vao giao dine Swagger UI
  # Mac dinh la /swagger-ui.html
  swagger-ui:
    path: /main/api-docs/swagger-ui.html

  # Thay doi duong dan file du lieu (apo-docs)
  # Mac dinh la /v3/api-docs
  api-docs:
    path: /main/api-docs/v3/api-docs

logging:
  file:
    path: ${LOG_PATH}